(defvar *product-data*
    '((("Authomobile" "Car" "1 unit")
       (("Car Body" "1 unit" 30)
        ("Engine" "1 unit" 30)
        ("Wheel & Tire" "4 units" 10))
        30)
       (("Automobile" "Motorcycle" "1 unit")
        (("Engine" "1 unit" 30)
         ("Steel" "10 lbs" 10)
         ("Wheel & Tire" "2 units" 10))
         50)
       (("Beverage" "Beer" "17 cans")
        (("Barley" "5 lbs" 40)
         ("Aluminium" "1 lb" 5))
         55)
       (("Beverage" "Bottled Milk" "8 bottles")
        (("Milk" "2 quarts" 65)
         ("Glass" "1 lb" 5))
         30)))

(defun get-product-data ()
    *product-data*)